name: Build LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: miktex/miktex:essential

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update MikTeX
      run: |
        mpm --admin --update
        miktex packages update-package-database
        miktex packages update

    - name: Compile LaTeX documents
      run: |
        mkdir output
        for file in *.tex; do
          pdflatex -output-directory=output "$file"
        done

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdfs
        path: output/*.pdf
